apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread
spec:
  replicas: 8 
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spread
  template:
    metadata:
      name: spread
      labels:
        app: spread
    spec:
      terminationGracePeriodSeconds: 1
      topologySpreadConstraints:
      - maxSkew: 1
        minDomains: 3
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: spread
      # Die affinity brauchts um die Controlplane nicht als Topology  zu haben. Weil sonst maxSkew gegen die ControlPlane (mit 0 Pods) geht
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key:  node-role.kubernetes.io/control-plane 
                operator: DoesNotExist
      containers:
      - name: image1
        image: erkules/nginxhostname:v1

