
apiVersion: v1
kind: Namespace
metadata:
  name:      myflux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:      myflux
  namespace: myflux
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluxi
  namespace: myflux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind:      ServiceAccount
  name:      myflux
  namespace: myflux

