apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks-base
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: capi-eks-base-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: capi-eks-base-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-base-control-plane
  namespace: default
spec:
  region: eu-central-1
  sshKeyName: ekstrouble
  #version: v1.17.3
  version: v1.21.2
  network:
    subnets:
    - id: "subnet-896df2e2"
    - id: "subnet-2568be58"
    - id: "subnet-4543fb08"
    vpc:
      id: "vpc-70d11b1b"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capi-eks-base-md-0
  namespace: default
spec:
  clusterName: capi-eks-base
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: capi-eks-base-md-0
      clusterName: capi-eks-base
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: capi-eks-base-md-0
        #version: v1.17.3
      version: v1.21.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: capi-eks-base-md-0
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: ekstrouble
      additionalTags:
        ApplicationID: DBCS-KAS
        ApplicationName: DBCS-KAS
        Contact: dbcs.support@deutschebahn.com
        CostReference: E-030272-995-01
        SecurityContactMail:  dbcs.support@deutschebahn.com
        TechnicalContactMail: dbcs.support@deutschebahn.com

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: capi-eks-base-md-0
  namespace: default
spec:
  template: {}
  #---
  #apiVersion: cluster.x-k8s.io/v1beta1
  #kind: MachinePool
  #metadata:
  #  name: capi-eks-base-pool-0
  #  namespace: default
  #spec:
  #  clusterName: capi-eks-base
  #  replicas: 3
  #  template:
  #    spec:
  #      bootstrap:
  #        dataSecretName: ""
  #      clusterName: capi-eks-base
  #      infrastructureRef:
  #        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  #        kind: AWSManagedMachinePool
  #        name: capi-eks-base-managed-pool-0
  #
  #
  #---
  ## AWS Managed MachinePool
  #apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  #kind: AWSManagedMachinePool
  #metadata:
  #  name: capi-eks-base-managed-pool-0
  #  namespace: default
  #spec:
  #  instanceType: t3.medium
  #  #subnet:
  #  additionalTags:
  #    ApplicationID: DBCS-KAS
  #    ApplicationName: DBCS-KAS
  #    Contact: dbcs.support@deutschebahn.com
  #    CostReference: E-030272-995-01
  #    SecurityContactMail:  dbcs.support@deutschebahn.com
  #
  #---
  ## AWS Machine Pool
