apiVersion: v1
kind: Namespace
metadata:
  name: donquota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: donquota
spec:
  hard:
    pods: 10
    configmaps: 5
    services: 4
    services.nodeports: 0
    services.loadbalancers: 0
    count/deployments.apps: 4
    requests.cpu: 1
    requests.memory: 1Gi
    requests.ephemeral-storage: 100Mi
    limits.cpu: 2
    limits.memory: 2Gi
    limits.ephemeral-storage: 2000Mi
    persistentvolumeclaims: 2
    default.storageclass.storage.k8s.io/requests.storage: 500Gi
---
