apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  labels:
     grafana_datasource: "1"
     namespace: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki:3100
