apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: policy-add-annotations
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: "add annotations"
    match:
      resources:
        kinds:
        - Pod
    mutate:   #<--- Jaja MUTATION
      patchStrategicMerge:
        metadata:
          annotations:
            iwas: here
    
