apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: validate-pod-label-app
spec:
  # Enforce oder Audit
  validationFailureAction: "Enforce"
  rules:
  - name: validate-pod-label-app
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pod muss ein app Label haben!"
      pattern:
        metadata:
          labels:
            app: "?*"
