apiVersion: v1
kind: Pod
metadata:
  name: gimmesecret-env
spec:
  terminationGracePeriodSeconds: 2
  serviceAccountName: sa2vault
  volumes:
  - name: geheim
    csi:
      driver:  secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: vaulta
  containers:
  - name: will
    volumeMounts:
    - name: geheim
      mountPath: /secret
      readOnly: true
        #    env:
        #    - name: username
        #      valueFrom:
        #        secretKeyRef:
        #          name: geheim
        #          key: name
    image: alpine
    command:
    - sleep
    - "5000"

