apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "devops"
    objects: |
      - objectName: "name"
        secretPath: "secret/data/devops/ich"
        secretKey: "name"
      - objectName: "passwort"
        secretPath: "secret/data/devops/ich"
        secretKey: "passwort"

