apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: mydashboard
  files:
  - kyverno-dashboard.json
  - policy-reporter-dashboard.json
  - policy-reporter-details-dashboard.json
  options:
    labels:
      grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
