apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginxwithexporter
  labels:
    team: example
spec:
  selector:
    matchLabels:
      app: nginxwithexporter
  endpoints:
  - port: metrics
  targetLabels:
  - kubernetesday
