apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configmap.fullname" . }}
data:
  lyric: |-
{{ .Files.Get "files/oha.txt" | indent 4 }}
  character : {{ .Values.character | default "zwerg" }}
