apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-example-multi
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: blackboxscraper
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  endpoints:
  - port: http
    interval: 15s
    path: /probe
    params:
      module:
      - http_2xx
      target:
      - "https://docker2.docker.zwerk.org"
    relabelings:
    - sourceLabels: [__param_target]
      targetLabel: instance
  - port: http
    interval: 15s
    path: /probe
    params:
      module:
      - http_2xx
      target:
      - "https://google.de"
    relabelings:
    - sourceLabels: [__param_target]
      targetLabel: instance

