apiVersion: v1
kind: Service
metadata:
  name: multi-port-example
spec:
  ports:
  - name: https
    port: 4443
    targetPort: 443
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: jaja
