apiVersion: v1
kind: Pod
metadata:
  name: hostport
spec:
  containers:
  - name: ping
    image: cgr.dev/chainguard/wolfi-base
    command:
    - sleep
    - "5000"
    ports:
    - containerPort: 80
      hostPort: 60111

