apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  containers:
  - name: ping
    image: cgr.dev/chainguard/wolfi-base
    securityContext:
      privileged: true
    command:
    - sleep
    - "5000"

