apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      name: harbor
      labels:
        app: harbor
    spec:
      terminationGracePeriodSeconds: 2
      #imagePullSecrets:
      #- name: pullman
      containers:
      - name: image1
        image: harbor.infra.zwerk.org/dockercamp/nginxhostname@sha256:80179485f086e15953d4fbc2dbaeb7ac8f5d56dc9f1bfd7f373b967dd9cae920
        imagePullPolicy: Always
