# Ab K8s 1.19
apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata:
  name: foo
spec:
  tls:
  - hosts:
    - DOCKERNAME.docker.zwerk.org
    secretName: docker
  rules:
  - host: DOCKERNAME.docker.zwerk.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: docker
            port:
              number: 80
---

apiVersion: v1
kind: Service
metadata:
  name: docker
spec: 
  selector:
    app: docker
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      name: www
      labels:
        app: docker
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: image1
        image: erkules/nginxhostname:v1
