apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-prio
spec:
  hard:
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["wichtiger"]

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nix-da
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
    - operator : NotIn
      scopeName: PriorityClass
      values: ["wichtiger"]

