apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  index.html: |
    <h1>hallo</h1>
    <loetkolben>
    aua
    </loetkolben>
  papa.html: |
    wer 
    reitet 
    durch 
    nacht und wind
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config2
data:
  index.html: |
    <h1>hallo</h1>
    <loetkolben>
    aua
    </loetkolben>
  mama.html: |
    eine
    schoene
    neue
    welt



---
apiVersion: v1
kind: Pod
metadata:
  name: projected-example
spec:
  containers:
  - name: www
    image: erkules/nginxhostname:v1
    volumeMounts:
    - name: all-together
      mountPath: /usr/share/nginx/html
  volumes:
  - name: all-together
    projected:
      sources:
      - configMap:
          name: config1
          items:
          - key: papa.html
            path: papa.html
      - configMap:
          name: config2
          items:
          - key: mama.html
            path: mama.html
  



